### ISSUE TITLE
Bad hook

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [shavkacagarikia/ClassicHolsteredWeaponsSystem#2]
https://github.com/shavkacagarikia/ClassicHolsteredWeaponsSystem/blob/88b8f7c9ecf52e57404706172b8bd63fdfb73411/main.cpp#L249

Actual signature: `bool TESObjectREFR::GetHasMandatoryAnimUpdate(TESObjectREFR *this)`
In particular, the first arg is not necessarily an actor. See [this crash log](https://pastebin.com/mzX2FWjC) for details.
Also your release dll is built in debug.

**Comment by shavkacagarikia** [comment]
its actually built in release, but I messed with build options and that's probably the reason. 
NiCloningProcess cp = {}; in standard release build, initializing this causes incorrect space allocation (at least I think so) for some of its members and then it causes crash. for debug build they are initialized correctly
